/* ==========================================================================
   app.js — boot, tab switching, theme toggle, cross-view navigation,
   and the Methods view (static prose driven by corpus metadata).
   ========================================================================== */
'use strict';

(async function () {

  const views = {
    map: () => MapView.activate(),
    trends: () => TrendsView.activate(),
    clusters: () => ClusterView.activate(),
    compare: () => CompareView.activate(),
    methods: () => {},
  };

  function switchView(name) {
    document.querySelectorAll('.tab').forEach(t =>
      t.classList.toggle('active', t.dataset.view === name));
    document.querySelectorAll('.view').forEach(v =>
      v.classList.toggle('active', v.id === 'view-' + name));
    (views[name] || views.map)();
  }

  document.querySelectorAll('.tab').forEach(t =>
    t.addEventListener('click', () => switchView(t.dataset.view)));

  ACC.on('switch-view', switchView);
  ACC.on('open-cluster', cid => { switchView('clusters'); ClusterView.open(cid); });

  /* --------------------------- methods view ----------------------------- */
  const PIPE = [
    { n: '01 · EXTRACT', t: 'Claims from abstracts', d: 'An LLM decomposes each abstract into atomic contribution claims — before any statistical analysis. Quality is human-validated (Fleiss\' κ = 0.844).' },
    { n: '02 · EMBED', t: 'SPECTER2 vectors', d: 'Each claim is embedded with SPECTER2, a scientific-document encoder, capturing what is being claimed rather than surface wording.' },
    { n: '03 · CLUSTER', t: 'UMAP + HDBSCAN, jointly', d: 'All years are clustered together so a cluster means the same thing early and late in the period. Cluster labels are generated by an LLM from each cluster\'s representative claims.' },
    { n: '04 · AGGREGATE', t: 'Document frequency', d: 'Per cluster and year: the share of papers contributing at least one claim. Drift is the change of this share over time.' },
  ];

  function renderMethods(m) {
    const years = m.years;
    const y0 = years[0], y1 = years.at(-1);
    const noisePct = (m.noiseShare * 100).toFixed(0) + '%';
    const reviewedN = ACC.state.data.clusters.filter(c => c.reviewed).length;
    const labelNote = reviewedN
      ? `all ${reviewedN} clusters carry LLM-generated labels, with raw c-TF-IDF descriptors kept everywhere`
      : 'labels are raw c-TF-IDF descriptors';
    const corpusRows = years.map((y, i) =>
      `<div class="corpus-row"><span>${y}</span>` +
      `<span>${m.papersPerYear[i].toLocaleString()}</span>` +
      `<span class="dim">${m.totalPapersPerYear ? 'of ' + m.totalPapersPerYear[i].toLocaleString() : '—'}</span>` +
      `<span>${m.claimsPerYear[i].toLocaleString()}</span></div>`).join('');

    // Auto-generated source statistics (venue · role · years · papers · claims).
    const sources = ACC.state.data.sources || [];
    const srcRows = sources.map(s => {
      const yr = (s.years && s.years.length)
        ? `${s.years[0]}–${s.years[s.years.length - 1]}` : '—';
      return `<div class="srcs-row"><span><span class="src-dot" style="background:${s.color}"></span>` +
        `${ACC.escapeHtml(s.venue)}</span>` +
        `<span>${s.role === 'clustered' ? 'jointly clustered' : 'overlaid (assigned)'}</span>` +
        `<span>${yr}</span><span>${(s.nPapers || 0).toLocaleString()}</span>` +
        `<span>${(s.nClaims || 0).toLocaleString()}</span></div>`;
    }).join('');
    const srcTotPapers = sources.reduce((a, s) => a + (s.nPapers || 0), 0).toLocaleString();
    const srcTotClaims = sources.reduce((a, s) => a + (s.nClaims || 0), 0).toLocaleString();

    document.getElementById('methods-body').innerHTML = `
      <div class="methods-section" style="gap:10px">
        <div class="methods-eyebrow">METHODS</div>
        <h1 class="methods-h1">Measuring scientific drift, one claim at a time</h1>
        <p class="methods-lead">Drift Inspector quantifies how a research field moves by tracking <b>Atomic Contribution Claims (ACCs)</b> — self-contained, contribution-bearing propositions extracted from paper abstracts — rather than keywords or whole papers. Claims are clustered jointly across all ${years.length} years of the corpus (${ACC.escapeHtml(m.subtitle || `${y0}–${y1}`)}), and each cluster's <i>document frequency</i> (the share of papers contributing at least one claim to it) is followed over time.</p>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Pipeline</h2>
        <div class="pipe-grid">
          ${PIPE.map(s => `<div class="pipe-card"><div class="pipe-n">${s.n}</div><div class="pipe-t">${s.t}</div><div class="pipe-d">${s.d}</div></div>`).join('')}
        </div>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Sources</h2>
        <p class="methods-p">The inspector combines one or more claim sources. <b>Jointly clustered</b> sources are embedded and clustered together to define the shared topic space; <b>overlaid</b> sources — other venues added later — are assigned to those existing topics by nearest centroid, so they can be compared and shown on the map without re-clustering. Toggle and highlight any source from the map's <i>Sources</i> menu.</p>
        <div class="corpus-table">
          <div class="srcs-row head"><span>SOURCE</span><span>ROLE</span><span>YEARS</span><span>PAPERS</span><span>CLAIMS</span></div>
          ${srcRows}
          <div class="srcs-row total"><span>Total</span><span></span><span></span><span>${srcTotPapers}</span><span>${srcTotClaims}</span></div>
        </div>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Clustered corpus</h2>
        <div class="corpus-table">
          <div class="corpus-row head"><span>YEAR</span><span>SAMPLED</span><span>OF TOTAL</span><span>CLAIMS</span></div>
          ${corpusRows}
          <div class="corpus-note">Papers are a stratified (venue × year) sample of the full main-conference corpus (seed 42); document-frequency shares divide by each year's sampled total, so they stay comparable across years. ${m.nClaims.toLocaleString()} claims in total; ${noisePct} remain unclustered — one-off contributions. ${m.nClusters} clusters; ${labelNote}.</div>
        </div>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Reading the views</h2>
        <p class="methods-p"><b class="serif">Map.</b> Every claim as a point in SPECTER2/UMAP space. Filter by year, recolor by drift trend — a relative scale built on the log-ratio of the ${y1} vs ${y0} share, so newly emerged or multi-fold-grown clusters read stronger than large clusters with modest growth (an ×8 change saturates the color). Search claims and titles, pin any point's card with a link to the source paper, isolate clusters from the legend (ctrl/cmd-click to combine).</p>
        <p class="methods-p"><b class="serif">Trends.</b> The ${y0} → ${y1} document-frequency shift as a butterfly chart, per-year trajectories for selected clusters (click bars or sparklines to add, capped at 12 lines for readability), and a sparkline overview of every cluster.</p>
        <p class="methods-p"><b class="serif">Clusters.</b> One cluster in depth: share of papers by year, its position in claim space, and all of its claims with links to the source papers — exportable as CSV.</p>
        <p class="methods-p"><b class="serif">Compare.</b> Two subsamples — a conference, an author, or a keyword set — side by side: each one's own topic profile, the gap between them, and how a subsample drifts across years. Leave the second subsample empty to study just one.</p>
        <p class="methods-p faint">A note on wording. Across the app, <b>share of papers</b> is a cluster's <i>document frequency</i> — the percentage of that year's sampled papers contributing at least one claim to the cluster — and <b>pp</b> (percentage points) is the change in that share from ${y0} to ${y1} (a move from 5% to 12% is +7&nbsp;pp). The drift colors and ▲/▼ arrows are driven by this measure; the “key terms” on the Clusters page are each cluster's raw c-TF-IDF descriptors; point positions come from the SPECTER2 / UMAP projection described above.</p>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Validation &amp; release</h2>
        <p class="methods-p">The pipeline and its validation are described in the accompanying paper (EMNLP 2026 System Demonstrations submission). Extraction quality is human-validated (three annotators, Fleiss' κ = 0.844); clustering is benchmarked against abstract-level baselines on an external taxonomy and is robust across a 36-cell hyperparameter grid. Code is released under MIT, the claim dataset under CC BY 4.0.</p>
        <p class="methods-p faint">The tool is corpus-agnostic: replace <span class="kbd-code">data/acc_data.json</span> (same schema) to explore another venue or field with no code changes.</p>
      </div>`;
  }

  /* ------------------------------- boot --------------------------------- */
  ACC.initTheme();

  document.getElementById('theme-toggle').addEventListener('click', () => ACC.toggleTheme());
  ACC.on('theme', () => {
    MapView.rebuildTheme();
    TrendsView.rebuildTheme();
    ClusterView.rebuildTheme();
    CompareView.rebuildTheme();
  });

  // ⌘K / Ctrl-K focuses the map search.
  document.addEventListener('keydown', e => {
    if ((e.metaKey || e.ctrlKey) && (e.key === 'k' || e.key === 'K')) {
      e.preventDefault();
      switchView('map');
      setTimeout(() => { const s = document.getElementById('map-search'); if (s) s.focus(); }, 50);
    }
  });

  /* Small fixed pill shown while claim texts stream in (split payload). */
  function loadPill() {
    if (!ACC.state.claimsPending) return;
    const pill = document.createElement('div');
    pill.className = 'load-pill';
    pill.textContent = 'loading claim texts…';
    document.body.appendChild(pill);
    ACC.on('claims-ready', () => pill.remove());
  }

  try {
    const data = await ACC.load();
    const m = data.meta;
    const totalPapers = m.papersPerYear.reduce((a, b) => a + b, 0);
    loadPill();

    // Brand and per-corpus strings come from the data file, so swapping
    // data/acc_data.json relabels the whole app.
    document.getElementById('brand-title').textContent = m.title || 'Drift Inspector';
    document.getElementById('brand-sub').textContent = m.subtitle || '';
    document.title = (m.title || 'Drift Inspector') + (m.subtitle ? ' — ' + m.subtitle : '');
    document.getElementById('butterfly-title').textContent =
      `Topic-share shift ${m.years[0]} → ${m.years.at(-1)}`;
    document.getElementById('intro-year0').textContent = m.years[0];
    document.getElementById('corpus-meta').textContent =
      `${m.nClaims.toLocaleString()} claims · ${m.nClusters} clusters · ${totalPapers.toLocaleString()} papers`;
    document.getElementById('noise-pct').textContent = (m.noiseShare * 100).toFixed(0) + '%';
    document.getElementById('intro-count').textContent =
      `${m.nClaims.toLocaleString()} CLAIMS · ONE POINT EACH`;

    renderMethods(m);
    switchView('map');
  } catch (err) {
    document.querySelector('.app').innerHTML =
      `<div class="detail-empty" style="padding:40px;text-align:center">Failed to load data: ${ACC.escapeHtml(err.message)}<br>` +
      `The website build needs to be served over HTTP (data is fetched from <code>data/acc_data.json</code>). ` +
      `Use the portable single-file build to open locally.</div>`;
    throw err;
  }
})();
